# This is a basic workflow to help you get started with Actions

name: cloudflare_dns

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      record_id:
        type: string
        default: '::1'
        required: true
      record_name:
        type: string
        default: '::1'
        required: true
      record_type:
        type: string
        default: '::1'
        required: true
      record_content:
        type: string
        default: '::1'
        required: true
      proxied:
        type: bool
        default: True
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: update_dns_records
        run: |
          pwd
          cd ${GITHUB_WORKSPACE}
          pwd
          python3 scripts/cloudflare_dns.py ${{ secrets.CLOUFLARETOKEN_DNS }} ${{ secrets.ZONE_ID_C }} ${{ github.event.inputs.record_id }} ${{ github.event.inputs.record_name }} ${{ github.event.inputs.record_type }} ${{ github.event.inputs.record_content }}  ${{ github.event.inputs.proxied }}
          
